### ISSUE TITLE
Little errors on text of the README.md file

### ISSUE THREAD

**Issue by FernandoTorresL** [PlatziMaster/challenge-html-01#7]
I found two little mistakes on the text of the README.md file:

- [x] **componente** to **componentes**

- [x] **compañefro** to **compañero**

So for educational purposes and practice this feature, I fix them and create this issue, and made the first PR from my team (@juancarico92 and me) to this challenge

The Pull Requests is this: #6

**Comment by nicobytes** [comment]
@FernandoTorresL Merged
